export const SCAN_CONFIG = {
  MAX_ASSETS: 15,
  MAX_MATCHES_PER_RULE: 8,
  MAX_ENTROPY_MATCHES: 10,
  ENTROPY_THRESHOLD: 3.5,
  FETCH_TIMEOUT_MS: 12000,
  ASSET_CONCURRENCY: 4,
};

export const SEVERITY_ORDER = ['critical', 'high', 'medium', 'low'];

export const SEVERITY_LABELS = {
  critical: 'Critical',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
};

export const EXPOSED_PATHS = [
  // ── Environment & configuration ──────────────────────────────────────────────
  '.env',
  '.env.local',
  '.env.production',
  '.env.development',
  '.env.test',
  '.env.staging',
  '.env.backup',
  '.env.old',
  '.env.example',
  '.env.sample',
  'env.json',
  'application.env',

  // ── Git / VCS ─────────────────────────────────────────────────────────────────
  '.git/config',
  '.git/HEAD',
  '.git/COMMIT_EDITMSG',
  '.git/packed-refs',
  '.git/refs/heads/main',
  '.git/refs/heads/master',
  '.git/logs/HEAD',
  '.gitignore',
  '.gitmodules',
  '.svn/entries',
  '.hg/hgrc',

  // ── Config files ─────────────────────────────────────────────────────────────
  'config.json',
  'config.yml',
  'config.yaml',
  'config.xml',
  'config.ini',
  'config.php',
  'config/database.yml',
  'config/secrets.yml',
  'config/application.yml',
  'configuration.json',
  'settings.json',
  'settings.py',
  'local_settings.py',
  'appsettings.json',
  'appsettings.Development.json',
  'web.config',

  // ── Secrets & credentials ─────────────────────────────────────────────────────
  'secrets.json',
  'secrets.yaml',
  'secrets.yml',
  'credentials.json',
  'credentials.yml',
  'credentials.xml',
  'keystore.jks',
  'keystore.p12',
  '.htpasswd',
  '.htaccess',
  'passwd',
  'shadow',
  'id_rsa',
  'id_ed25519',
  'private_key.pem',
  'server.key',
  'server.pem',
  'ssl.key',
  'certificate.key',
  'private.key',

  // ── Database ──────────────────────────────────────────────────────────────────
  'dump.sql',
  'database.sql',
  'db.sql',
  'backup.sql',
  'data.sql',
  'mysqldump.sql',
  'pg_dump.sql',
  'mongo_dump.json',

  // ── Backup / archives ─────────────────────────────────────────────────────────
  'backup.zip',
  'backup.tar.gz',
  'backup.tar',
  'backup.tgz',
  'backup.7z',
  'backup.rar',
  'site.zip',
  'source.zip',
  'www.zip',
  'public.zip',
  'app.zip',
  'deploy.zip',
  'release.tar.gz',
  'archive.zip',
  'old.zip',

  // ── Docker & containerisation ─────────────────────────────────────────────────
  'docker-compose.yml',
  'docker-compose.yaml',
  'docker-compose.prod.yml',
  'docker-compose.override.yml',
  'Dockerfile',
  '.dockerignore',

  // ── Kubernetes / infrastructure ───────────────────────────────────────────────
  'k8s.yml',
  'kubernetes.yml',
  'deploy.yml',
  'deployment.yaml',
  'terraform.tfvars',
  'terraform.tfstate',
  '.terraform/terraform.tfstate',
  'ansible.cfg',
  'inventory.ini',
  'vars.yml',
  'vault.yml',

  // ── CI/CD ─────────────────────────────────────────────────────────────────────
  '.travis.yml',
  '.circleci/config.yml',
  '.github/workflows/deploy.yml',
  'Jenkinsfile',
  '.gitlab-ci.yml',
  '.drone.yml',
  'bitbucket-pipelines.yml',

  // ── API documentation ─────────────────────────────────────────────────────────
  'swagger.json',
  'swagger.yaml',
  'openapi.json',
  'openapi.yaml',
  'api-docs/swagger.json',
  'api-docs/',
  'api/swagger.json',
  'v1/swagger.json',
  'v2/swagger.json',
  'api-docs/openapi.json',
  'swagger-ui/',
  'redoc',
  'graphql-schema.json',
  'schema.graphql',
  'schema.json',

  // ── Spring Boot / Java ────────────────────────────────────────────────────────
  'actuator/env',
  'actuator/info',
  'actuator/health',
  'actuator/beans',
  'actuator/configprops',
  'actuator/mappings',
  'actuator/metrics',
  'actuator/loggers',
  'actuator/dump',
  'actuator/threaddump',
  'actuator/heapdump',
  'actuator/shutdown',
  'jolokia',
  'jolokia/exec/java.lang:type=Runtime/systemProperties',

  // ── PHP / WordPress ───────────────────────────────────────────────────────────
  'wp-config.php',
  'wp-config.php.bak',
  'wp-config.php.old',
  'wp-config.php~',
  'phpinfo.php',
  'info.php',
  'test.php',
  'php-info.php',
  'php.php',
  'admin.php',
  'adminer.php',
  'adminer-4.7.9.php',
  'phpmyadmin/',
  'phpMyAdmin/',
  'pma/',

  // ── Debug / development endpoints ─────────────────────────────────────────────
  'server-status',
  'server-info',
  'debug',
  'debug/',
  '_debug',
  '_profiler/',
  '__debug__/',
  '__webpack_hmr',
  'webpack-dev-server',
  'sockjs-node',
  'livereload',
  'console',
  '.well-known/security.txt',
  'security.txt',
  'SECURITY.md',
  'CHANGELOG.md',
  'CHANGELOG',

  // ── Node.js / npm ─────────────────────────────────────────────────────────────
  'package.json',
  'package-lock.json',
  'yarn.lock',
  'npm-debug.log',
  'yarn-debug.log',
  'yarn-error.log',
  '.npmrc',
  '.yarnrc',
  'node_modules/.package-lock.json',

  // ── Python ────────────────────────────────────────────────────────────────────
  'requirements.txt',
  'Pipfile',
  'Pipfile.lock',
  'pyproject.toml',
  'setup.cfg',
  '__pycache__/',
  'manage.py',
  'wsgi.py',
  'gunicorn.conf.py',

  // ── Ruby ──────────────────────────────────────────────────────────────────────
  'Gemfile',
  'Gemfile.lock',
  'config/database.yml',
  'config/master.key',
  'config/credentials.yml.enc',

  // ── Log files ─────────────────────────────────────────────────────────────────
  'error.log',
  'access.log',
  'debug.log',
  'app.log',
  'application.log',
  'server.log',
  'laravel.log',
  'storage/logs/laravel.log',
  'var/log/app.log',
  'logs/error.log',
];
